
GET http://localhost:5000/


### Register a user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username" : "mangesh",
    "password" : "123123123"
}


### Login a user
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username" : "mangesh",
    "password" : "123123123"
}


### Get all todos
GET http://localhost:5000/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzg4NzYwNDE0LCJleHAiOjE3ODg4NDY4MTR9.bllwr3FyDG2wg1DmvOLngI4DxVkEn-z5a8HmFuOwax4


### Insert a todo
POST http://localhost:5000/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzg4NzYwNDE0LCJleHAiOjE3ODg4NDY4MTR9.bllwr3FyDG2wg1DmvOLngI4DxVkEn-z5a8HmFuOwax4

{
    "task" : "Go to class"
}
